// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeId } from "./NodeId";
import type { NodeKind } from "./NodeKind";

export type NodeMeta = { id: NodeId, kind: NodeKind, path: string, title: string, tags: Array<string>, created_at: string | null, updated_at: string | null, color: string | null, };
