// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResyncReport = { scanned_files: bigint, created_meta: bigint, updated_meta: bigint, orphan_meta: bigint, orphan_files: bigint, };
